os: linux
sudo: required
dist: xenial
language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - python3
      - python3-pip
      - cmake-data
      - cmake

script:
  - pip3 install -U conan
  - conan
  - conan --version
  - mkdir build-dir && cd build-dir
  - cmake -DCMAKE_INSTALL_PREFIX="$(pwd)/root" ..
  - make
  - make install
